# https://taskfile.dev

version: "3"

vars:
  EXAMPLE_DIR: ./example/
  TESTING_DIR: ./testing/

tasks:
  testing:
    aliases: [t]
    cmds:
      - go run "{{.TESTING_DIR}}"
  example:
    aliases: [x]
    cmds:
      - go run "{{.EXAMPLE_DIR}}"
